// =============================================
// VIRTUALTWIN STRIPE SETUP SCRIPT
// Creates all 8 products + prices automatically
// Run: npx ts-node scripts/setupStripe.ts
// =============================================

import Stripe from 'stripe';
import * as fs from 'fs';
import * as path from 'path';

// Initialize Stripe with your secret key
const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!, {
    apiVersion: '2023-10-16'
});

interface PlanConfig {
    name: string;
    founderPrice: number;
    publicPrice: number;
    description: string;
    features: string[];
}

const PLANS: PlanConfig[] = [
    {
        name: 'Esploratore',
        founderPrice: 3900, // €39 in cents
        publicPrice: 7900,   // €79 in cents
        description: 'Per chi inizia a scalare',
        features: ['1 Clone AI', '1K msg/mese', '1 Canale', 'Email Support']
    },
    {
        name: 'Pioniere',
        founderPrice: 9700,  // €97 in cents
        publicPrice: 19700,  // €197 in cents
        description: 'Il più scelto dai professionisti',
        features: ['1 Clone AI', '5K msg/mese', '3 Canali', 'A/B Testing 20%']
    },
    {
        name: 'Conquistatore',
        founderPrice: 19700,  // €197 in cents
        publicPrice: 39700,   // €397 in cents
        description: 'Per chi domina il mercato',
        features: ['3 Cloni AI', '20K msg/mese', 'Priority Support', 'API Access']
    },
    {
        name: 'Imperatore',
        founderPrice: 59500,  // €595 in cents
        publicPrice: 79700,   // €797 in cents
        description: 'Per costruire imperi',
        features: ['10 Cloni AI', '50K msg/mese', 'White-label', 'Account Manager']
    }
];

interface CreatedPrice {
    plan: string;
    tier: 'founder' | 'public';
    priceId: string;
    productId: string;
    amount: number;
}

async function createProduct(plan: PlanConfig, tier: 'founder' | 'public'): Promise<CreatedPrice> {
    const amount = tier === 'founder' ? plan.founderPrice : plan.publicPrice;
    const productName = `VirtualTwin ${plan.name} ${tier === 'founder' ? 'Founder' : ''}`.trim();

    console.log(`Creating ${productName}...`);

    // Create product
    const product = await stripe.products.create({
        name: productName,
        description: plan.description,
        metadata: {
            plan: plan.name.toLowerCase(),
            tier: tier,
            features: plan.features.join(', ')
        }
    });

    // Create price
    const price = await stripe.prices.create({
        product: product.id,
        unit_amount: amount,
        currency: 'eur',
        recurring: {
            interval: 'month'
        },
        metadata: {
            plan: plan.name.toLowerCase(),
            tier: tier
        }
    });

    console.log(`✅ Created: ${productName} - ${price.id}`);

    return {
        plan: plan.name.toLowerCase(),
        tier,
        priceId: price.id,
        productId: product.id,
        amount
    };
}

async function updateStripeConfig(prices: CreatedPrice[]): Promise<void> {
    const configPath = path.join(__dirname, '../lib/stripeConfig.ts');

    const priceMap: Record<string, Record<string, string>> = {};

    for (const price of prices) {
        if (!priceMap[price.plan]) {
            priceMap[price.plan] = {};
        }
        priceMap[price.plan][price.tier] = price.priceId;
    }

    const configContent = `// =============================================
// VIRTUALTWIN STRIPE CONFIGURATION
// Auto-generated by setupStripe.ts
// Generated: ${new Date().toISOString()}
// =============================================

export const STRIPE_PRICES = {
    esploratore: {
        founder: {
            monthly: '${priceMap.esploratore?.founder || ''}',
            yearly: '' // Add yearly later
        },
        public: {
            monthly: '${priceMap.esploratore?.public || ''}',
            yearly: ''
        }
    },
    pioniere: {
        founder: {
            monthly: '${priceMap.pioniere?.founder || ''}',
            yearly: ''
        },
        public: {
            monthly: '${priceMap.pioniere?.public || ''}',
            yearly: ''
        }
    },
    conquistatore: {
        founder: {
            monthly: '${priceMap.conquistatore?.founder || ''}',
            yearly: ''
        },
        public: {
            monthly: '${priceMap.conquistatore?.public || ''}',
            yearly: ''
        }
    },
    imperatore: {
        founder: {
            monthly: '${priceMap.imperatore?.founder || ''}',
            yearly: ''
        },
        public: {
            monthly: '${priceMap.imperatore?.public || ''}',
            yearly: ''
        }
    }
} as const;

export type PlanTier = keyof typeof STRIPE_PRICES;
export type PricingType = 'founder' | 'public';
export type BillingInterval = 'monthly' | 'yearly';

export function getStripePriceId(
    plan: PlanTier,
    isFounder: boolean,
    billing: BillingInterval = 'monthly'
): string {
    const type: PricingType = isFounder ? 'founder' : 'public';
    return STRIPE_PRICES[plan][type][billing];
}

export const DISPLAY_PRICES = {
    esploratore: { founder: 39, public: 79 },
    pioniere: { founder: 97, public: 197 },
    conquistatore: { founder: 197, public: 397 },
    imperatore: { founder: 595, public: 797 }
} as const;

export const FOUNDER_CONFIG = {
    totalSpots: 153,
    deadline: '2026-03-31T23:59:59',
    lifetimeLock: true
} as const;
`;

    fs.writeFileSync(configPath, configContent);
    console.log(`\n✅ Updated lib/stripeConfig.ts with new Price IDs!`);
}

async function main(): Promise<void> {
    console.log('🚀 VirtualTwin Stripe Setup\n');
    console.log('Creating 8 products (4 plans × 2 tiers)...\n');

    const createdPrices: CreatedPrice[] = [];

    for (const plan of PLANS) {
        // Create Founder price
        const founderPrice = await createProduct(plan, 'founder');
        createdPrices.push(founderPrice);

        // Create Public price
        const publicPrice = await createProduct(plan, 'public');
        createdPrices.push(publicPrice);
    }

    console.log('\n📋 Summary:');
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');

    for (const price of createdPrices) {
        console.log(`${price.plan} (${price.tier}): ${price.priceId}`);
    }

    // Update stripeConfig.ts
    await updateStripeConfig(createdPrices);

    console.log('\n✅ All done! 8 products created in Stripe.');
    console.log('🔗 View in Stripe Dashboard: https://dashboard.stripe.com/products');
}

main().catch(console.error);
